[build]
  command = "ng build --configuration production"
  publish = "dist/bagaleria/browser"

# Reescrita para apps SPA (Angular, React, Vue)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200